export const ukCities = [
  "Aberdeen",
  "Belfast",
  "Birmingham",
  "Brighton",
  "Bristol",
  "Cambridge",
  "Cardiff",
  "Edinburgh",
  "Glasgow",
  "Leeds",
  "Leicester",
  "Liverpool",
  "London",
  "Manchester",
  "Newcastle",
  "Nottingham",
  "Oxford",
  "Sheffield",
  "Southampton",
  "York",
];

export const usCities = [
  "Albuquerque",
  "Atlanta",
  "Austin",
  "Baltimore",
  "Boston",
  "Charlotte",
  "Chicago",
  "Cincinnati",
  "Cleveland",
  "Columbus",
  "Dallas",
  "Denver",
  "Detroit",
  "Houston",
  "Indianapolis",
  "Jacksonville",
  "Kansas City",
  "Las Vegas",
  "Los Angeles",
  "Miami",
  "Milwaukee",
  "Minneapolis",
  "Nashville",
  "New Orleans",
  "New York",
  "Orlando",
  "Philadelphia",
  "Phoenix",
  "Pittsburgh",
  "Portland",
  "Raleigh",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Seattle",
  "St. Louis",
  "Tampa",
  "Tucson",
  "Washington DC",
];
